# Generated by Django 5.2 on 2026-03-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_clasificacionvigencia_alter_aliados_aliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='codigo_meta',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
