# Generated by Django 5.2 on 2026-03-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_clasificacionindicadormga_codigo_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='publico_priorizado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='que_ofrece',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='quienes_pueden_participar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto_contrapartida',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
