# Generated by Django 5.2 on 2026-03-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_convocatorias_enlace_convocatoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convocatorias',
            old_name='objectivo',
            new_name='objetivo',
        ),
    ]
