# Generated by Django 5.2 on 2026-03-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0010_alter_convocatorias_enlace_convocatoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='monto',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto_contrapartida',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='valor_proyecto',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
