# Generated by Django 5.2 on 2026-03-24 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0012_convocatorias_monto_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionFuenteFinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_fuente', models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional')], max_length=3, verbose_name='Tipo de Fuente')),
                ('subtipo', models.CharField(blank=True, choices=[('RP', 'Recursos Propios'), ('PGN', 'Presupuesto General de la Nación'), ('SGR', 'Sistema General de Regalías'), ('CRE', 'Crédito'), ('COO', 'Cooperación Internacional'), ('DON', 'Donación'), ('OTR', 'Otro')], max_length=3, null=True, verbose_name='Subtipo de Fuente')),
                ('fuente', models.CharField(max_length=250, verbose_name='Fuente de Financiacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clasificación Fuente de Financiación',
                'verbose_name_plural': 'Clasificación Fuentes de Financiación',
            },
        ),
        migrations.CreateModel(
            name='FuenteFinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_comprometido', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Valor Comprometido')),
                ('valor_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Valor Pagado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.clasificacionfuentefinanciacion', verbose_name='Fuente de Financiación')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.proyecto')),
                ('vigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.clasificacionvigencia')),
            ],
            options={
                'verbose_name': 'Fuente de Financiación',
                'verbose_name_plural': 'Fuentes de Financiación',
                'unique_together': {('vigencia', 'fuente', 'proyecto')},
            },
        ),
    ]
