# Generated by Django 5.2 on 2026-03-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0016_alter_convocatorias_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatorias',
            name='estado',
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='contacto',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
