# Generated by Django 5.2 on 2026-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0019_alter_convocatorias_aliados_alter_proyecto_aliados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatorias',
            name='observaciones_monto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='bpin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
