# Generated by Django 5.2 on 2026-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0021_comentariosproyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariosproyectos',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
