# Generated by Django 5.2 on 2026-05-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0023_alter_convocatorias_enlace_convocatoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='dependencia',
            field=models.ManyToManyField(blank=True, to='contenido.dependencia'),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='sectores',
            field=models.ManyToManyField(blank=True, to='contenido.sectores'),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='segmento',
            field=models.ManyToManyField(blank=True, to='contenido.segmentos'),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='ubicacion',
            field=models.ManyToManyField(blank=True, to='contenido.ubicacion'),
        ),
    ]
