# Generated by Django 5.2 on 2026-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0025_alter_clasificacionindicadormga_codigo_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='contacto',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
