"""
Django settings for convocatorias_seguimiento project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# --- para unfold


from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d%h3+&m)dh21imvzgr&g=q4uv&^^)5m!aaf=j=lh$kq24qlawt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contenido',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'convocatorias_seguimiento.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'convocatorias_seguimiento.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Agregar esto

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    "https://chase-nondrinkable-editorially.ngrok-free.dev"
]

UNFOLD = {
    "SITE_TITLE": "Panel de Administración",
    "SITE_HEADER": "Panel de Administración",

    "NAVIGATION": [
        # ── Convocatorias y Proyectos ────────────────────────────────────────
        {
            "title": _("Convocatorias"),
            "separator": True,
            "icon": "description",
            "items": [
                {
                    "title": _("Convocatorias"),
                    "icon": "article",
                    "link": lambda request: reverse_lazy("admin:contenido_convocatorias_changelist"),
                },
                {
                    "title": _("Proyectos"),
                    "icon": "folder_open",
                    "link": lambda request: reverse_lazy("admin:contenido_proyecto_changelist"),
                },
                {
                    "title": _("Beneficiarios"),
                    "icon": "group",
                    "link": lambda request: reverse_lazy("admin:contenido_beneficiarios_changelist"),
                },
                {
                    "title": _("Indicadores MGA"),
                    "icon": "bar_chart",
                    "link": lambda request: reverse_lazy("admin:contenido_indicadormga_changelist"),
                },
            ],
        },

        # ── Parámetros ───────────────────────────────────────────────────────
        {
            "title": _("Parámetros"),
            "separator": True,
            "icon": "settings",
            "items": [
                {
                    "title": _("Estados"),
                    "icon": "toggle_on",
                    "link": lambda request: reverse_lazy("admin:contenido_estado_changelist"),
                },
                {
                    "title": _("Segmentos"),
                    "icon": "category",
                    "link": lambda request: reverse_lazy("admin:contenido_segmentos_changelist"),
                },
                {
                    "title": _("Sectores"),
                    "icon": "domain",
                    "link": lambda request: reverse_lazy("admin:contenido_sectores_changelist"),
                },
                {
                    "title": _("Ubicaciones"),
                    "icon": "place",
                    "link": lambda request: reverse_lazy("admin:contenido_ubicacion_changelist"),
                },
                {
                    "title": _("Municipios"),
                    "icon": "location_city",
                    "link": lambda request: reverse_lazy("admin:contenido_municipios_changelist"),
                },
                {
                    "title": _("Dependencias"),
                    "icon": "account_tree",
                    "link": lambda request: reverse_lazy("admin:contenido_dependencia_changelist"),
                },
                {
                    "title": _("Responsables"),
                    "icon": "manage_accounts",
                    "link": lambda request: reverse_lazy("admin:contenido_responsable_changelist"),
                },
                {
                    "title": _("Aliados"),
                    "icon": "handshake",
                    "link": lambda request: reverse_lazy("admin:contenido_aliados_changelist"),
                },
                {
                    "title": _("Tipos de Beneficiario"),
                    "icon": "person_search",
                    "link": lambda request: reverse_lazy("admin:contenido_clasificacionbeneficiario_changelist"),
                },
                {
                    "title": _("Clasificación Indicadores MGA"),
                    "icon": "analytics",
                    "link": lambda request: reverse_lazy("admin:contenido_clasificacionindicadormga_changelist"),
                },
            ],
        },
    ],
}