"""
Django settings for convocatorias_seguimiento project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv
import os

import os
import dj_database_url
from pathlib import Path

# --- para unfold


from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_PATH = Path(__file__).resolve().parents[2] / ".env"

print("Buscando .env en:", ENV_PATH)

load_dotenv(ENV_PATH)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d%h3+&m)dh21imvzgr&g=q4uv&^^)5m!aaf=j=lh$kq24qlawt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'contenido',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'convocatorias_seguimiento.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'convocatorias_seguimiento.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
            ),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Agregar esto

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    "https://chase-nondrinkable-editorially.ngrok-free.dev"
]


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


UNFOLD = {
    "SIDEBAR": {
        "navigation": [
            {
                "title": "Seguimiento",
                "icon": "track_changes",
                "items": [
                    {
                        "title": "Convocatorias",
                        "icon": "campaign",
                        "link": "/admin/contenido/convocatorias/",
                    },
                    {
                        "title": "Proyectos",
                        "icon": "folder_open",
                        "link": "/admin/contenido/proyecto/",
                    },
                ],
            },
            {
                "title": "Parámetros",
                "icon": "settings",
                "items": [
                    {
                        "title": "Dependencias",
                        "icon": "account_tree",
                        "link": "/admin/contenido/dependencia/",
                    },
                    {
                        "title": "Responsables",
                        "icon": "person",
                        "link": "/admin/contenido/responsable/",
                    },
                    {
                        "title": "Aliados",
                        "icon": "handshake",
                        "link": "/admin/contenido/aliados/",
                    },
                    {
                        "title": "Segmentos",
                        "icon": "donut_small",
                        "link": "/admin/contenido/segmentos/",
                    },
                    {
                        "title": "Sectores",
                        "icon": "category",
                        "link": "/admin/contenido/sectores/",
                    },
                    {
                        "title": "Estados",
                        "icon": "flag",
                        "link": "/admin/contenido/estado/",
                    },
                    {
                        "title": "Municipios",
                        "icon": "location_city",
                        "link": "/admin/contenido/municipios/",
                    },
                    {
                        "title": "Ubicaciones",
                        "icon": "place",
                        "link": "/admin/contenido/ubicacion/",
                    },
                    {
                        "title": "Tipos de beneficiario",
                        "icon": "group",
                        "link": "/admin/contenido/clasificacionbeneficiario/",
                    },
                    {
                        "title": "Vigencias",
                        "icon": "calendar_month",
                        "link": "/admin/contenido/clasificacionvigencia/",
                    },
                    {
                        "title": "Indicadores MGA",
                        "icon": "bar_chart",
                        "link": "/admin/contenido/clasificacionindicadormga/",
                    },
                ],
            },
        ]
    },
}