"""
Django settings for convocatorias_seguimiento project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv
import os
import dj_database_url
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_PATH = Path(__file__).resolve().parents[2] / ".env"

load_dotenv(ENV_PATH)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'djmoney',
    'contenido',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LANGUAGE_CODE = "es"

USE_I18N = True

LANGUAGES = (
    ("en", _("English")),
    ("es", _("Spanish")),
)

ROOT_URLCONF = 'convocatorias_seguimiento.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'convocatorias_seguimiento.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
            ),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Agregar esto

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    "https://chase-nondrinkable-editorially.ngrok-free.dev"
]


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


UNFOLD = {
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "SHOW_LANGUAGES": True,
    "BORDER_RADIUS": "6px",
    "SITE_TITLE": "Convocatorias",
    "SITE_HEADER": "Convocatorias",
    "SITE_SYMBOL": "campaign",
    "SIDEBAR": {
        "show_search" : True,
        "command_search": True,
        "navigation": [
            {
                "separator":True,
                "title": "Seguimiento",
                "icon": "track_changes",
                "items": [
                    {
                        "title": "Convocatorias",
                        "icon": "campaign",
                        "link": "/admin/contenido/convocatorias/",
                    },
                    {
                        "title": "Proyectos",
                        "icon": "folder_open",
                        "link": "/admin/contenido/proyecto/",
                    },
                ],
            },
            {
                "title": "Parámetros",
                "icon": "settings",
                "items": [
                    {
                        "title": "Dependencias",
                        "icon": "account_tree",
                        "link": "/admin/contenido/dependencia/",
                    },
                    {
                        "title": "Responsables",
                        "icon": "person",
                        "link": "/admin/contenido/responsable/",
                    },
                    {
                        "title": "Fuentes de Financiación",
                        "icon":"payments",
                        "link": "/admin/contenido/clasificacionfuentefinanciacion/"
                    },
                    {
                        "title": "Clasificación Aliados",
                        "icon": "bookmark",
                        "link": "/admin/contenido/clasificacionaliados/",
                    },
                    {
                        "title": "Aliados",
                        "icon": "handshake",
                        "link": "/admin/contenido/aliados/",
                    },
                    {
                        "title": "Segmentos",
                        "icon": "donut_small",
                        "link": "/admin/contenido/segmentos/",
                    },
                    {
                        "title": "Sectores",
                        "icon": "category",
                        "link": "/admin/contenido/sectores/",
                    },
                    {
                        "title": "Municipios",
                        "icon": "location_city",
                        "link": "/admin/contenido/municipios/",
                    },
                    {
                        "title": "Ubicaciones",
                        "icon": "place",
                        "link": "/admin/contenido/ubicacion/",
                    },
                    {
                        "title": "Tipos de beneficiario",
                        "icon": "group",
                        "link": "/admin/contenido/clasificacionbeneficiario/",
                    },
                    {
                        "title": "Vigencias",
                        "icon": "calendar_month",
                        "link": "/admin/contenido/clasificacionvigencia/",
                    },
                    {
                        "title": "Indicadores MGA",
                        "icon": "bar_chart",
                        "link": "/admin/contenido/clasificacionindicadormga/",
                    },
                ],
            },
        ]
    },
    "COLORS": {
    "base": {
        "50":  "oklch(98.5% 0.003 249.372)",
        "100": "oklch(96.7% 0.005 249.372)",
        "200": "oklch(92.8% 0.009 249.372)",
        "300": "oklch(87.2% 0.013 249.372)",
        "400": "oklch(70.7% 0.022 249.372)",
        "500": "oklch(55.1% 0.028 249.372)",
        "600": "oklch(44.6% 0.031 249.372)",
        "700": "oklch(37.3% 0.034 249.372)",
        "800": "oklch(27.8% 0.033 249.372)",
        "900": "oklch(21.0% 0.034 249.372)",
        "950": "oklch(13.0% 0.028 249.372)",
    },
    "primary": {
        "50":  "oklch(97.2% 0.01  249.372)",
        "100": "oklch(94.0% 0.018 249.372)",
        "200": "oklch(88.0% 0.035 249.372)",
        "300": "oklch(78.0% 0.065 249.372)",
        "400": "oklch(65.0% 0.1   249.372)",
        "500": "oklch(52.0% 0.13  249.372)",
        "600": "oklch(42.0% 0.14  249.372)",
        "700": "oklch(35.0% 0.13  249.372)",
        "800": "oklch(27.0% 0.11  249.372)",
        "900": "oklch(20.0% 0.085 249.372)",
        "950": "oklch(14.0% 0.06  249.372)",
    },
    "font": {
        "subtle-light":    "var(--color-base-500)",
        "subtle-dark":     "var(--color-base-400)",
        "default-light":   "var(--color-base-600)",
        "default-dark":    "var(--color-base-300)",
        "important-light": "var(--color-base-900)",
        "important-dark":  "var(--color-base-100)",
    },
},
}