# Generated by Django 5.2 on 2026-03-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadormga',
            name='meta_proyecto',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
    ]
