# Generated by Django 5.2 on 2026-03-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_indicadormga_meta_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionVigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.IntegerField(null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vigencia',
                'verbose_name_plural': 'Vigencias',
            },
        ),
        migrations.AlterField(
            model_name='aliados',
            name='aliado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='dependencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='municipios',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='responsable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sectores',
            name='sector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='segmentos',
            name='segmento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='indicadormga',
            name='vigencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.clasificacionvigencia'),
        ),
    ]
