# Generated by Django 5.2 on 2026-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_convocatorias_publico_priorizado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificacionindicadormga',
            old_name='meta_indicador',
            new_name='meta_cuatrienio',
        ),
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='decripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='medido_a_atraves_de',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='meta_fisica_esperada_2024',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='meta_fisica_esperada_2025',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='meta_fisica_esperada_2026',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='meta_fisica_esperada_2027',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clasificacionindicadormga',
            name='tipo_acumulacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
