# Generated by Django 5.2 on 2026-03-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_rename_meta_indicador_clasificacionindicadormga_meta_cuatrienio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionAliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_aliado', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clasificacion Aliado',
                'verbose_name_plural': 'Clasificacion Aliados',
            },
        ),
        migrations.AddField(
            model_name='convocatorias',
            name='aliados',
            field=models.ManyToManyField(to='contenido.aliados'),
        ),
        migrations.AlterField(
            model_name='aliados',
            name='aliado',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='aliados',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.clasificacionaliados'),
        ),
    ]
