# Generated by Django 5.2 on 2026-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_clasificacionaliados_convocatorias_aliados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatorias',
            name='enlace_convocatoria',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='convocatorias',
            name='enlace_del_actor',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='convocatorias',
            name='estado_monto',
            field=models.CharField(choices=[('ES', 'Especifica'), ('NE', 'No especifica')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='convocatorias',
            name='objectivo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='contacto',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
