# Generated by Django 5.2 on 2026-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_rename_objectivo_convocatorias_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='enlace_convocatoria',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='enlace_del_actor',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
