# Generated by Django 5.2 on 2026-03-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_fuentefinanciacion_valor_comprometido_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='monto_contrapartida',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='monto_contrapartida_currency',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='valor_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='valor_proyecto_currency',
        ),
    ]
