# Generated by Django 5.2 on 2026-03-24 05:11

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0015_remove_proyecto_monto_contrapartida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='monto',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, default_currency='COP', max_digits=19, null=True),
        ),
    ]
