# Generated by Django 5.2 on 2026-04-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0017_remove_convocatorias_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatorias',
            name='imagen_convocatoria',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='aliados',
            field=models.ManyToManyField(blank=True, null=True, to='contenido.aliados'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_envio_postulacion_proyecto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_envio_subsanciones_proyecto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_publicacion_resultados_proyecto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_solicitud_subsanacion_proyecto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
