# Generated by Django 5.2 on 2026-05-12 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0018_convocatorias_imagen_convocatoria_proyecto_aliados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='aliados',
            field=models.ManyToManyField(blank=True, to='contenido.aliados'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='aliados',
            field=models.ManyToManyField(blank=True, to='contenido.aliados'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.ManyToManyField(blank=True, to='contenido.dependencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
