# Generated by Django 5.2 on 2026-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0022_comentariosproyectos_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='enlace_convocatoria',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='enlace_del_actor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='municipios',
            field=models.ManyToManyField(blank=True, to='contenido.municipios'),
        ),
    ]
