# Generated by Django 5.2 on 2026-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0024_alter_convocatorias_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionindicadormga',
            name='codigo_meta',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='convocatorias',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
